kratos:
  development: true
  automigration:
    enabled: true
    type: job
  config:
    serve:
      public:
        base_url: http://localhost:4433/
        cors:
          enabled: true
      admin:
        base_url: http://localhost:4434/
    dsn: "postgres://mysaas:mysaas-dev@postgres-postgresql.ory.svc.cluster.local:5432/mysaas?sslmode=disable&search_path=kratos"
    identity:
      default_schema_id: user
      schemas:
        - id: user
          url: base64://eyIkaWQiOiJodHRwczovL3NjaGVtYXMub3J5LnNoL3ByZXNldHMva3JhdG9zL2lkZW50aXR5LnVzZXIuc2NoZW1hLmpzb24iLCIkc2NoZW1hIjoiaHR0cDovL2pzb24tc2NoZW1hLm9yZy9kcmFmdC0wNy9zY2hlbWEjIiwidGl0bGUiOiJVc2VyIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsidHJhaXRzIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImVtYWlsIjp7InR5cGUiOiJzdHJpbmciLCJmb3JtYXQiOiJlbWFpbCIsInRpdGxlIjoiRS1NYWlsIiwib3J5LnNoL2tyYXRvcyI6eyJjcmVkZW50aWFscyI6eyJwYXNzd29yZCI6eyJpZGVudGlmaWVyIjp0cnVlfX0sInZlcmlmaWNhdGlvbiI6eyJ2aWEiOiJlbWFpbCJ9LCJyZWNvdmVyeSI6eyJ2aWEiOiJlbWFpbCJ9fX19LCJyZXF1aXJlZCI6WyJlbWFpbCJdfX19fQ==
    courier:
      smtp:
        connection_uri: "smtp://mailhog-mailhog.ory.svc.cluster.local:1025/?disable_starttls=true"
    selfservice:
      default_browser_return_url: http://localhost:3000/
      flows:
        registration:
          enabled: true
          ui_url: http://localhost:3000/registration
        login:
          ui_url: http://localhost:3000/login
        settings:
          ui_url: http://localhost:3000/settings
    session:
      lifespan: 24h

secret:
  enabled: true

service:
  admin:
    type: LoadBalancer
    port: 4434
  public:
    type: LoadBalancer
    port: 4433